# Enable C++ support
language: cpp
# OS selection
os:
  - linux
  - osx
# Compiler selection
compiler:
  #- clang
  - gcc
# environment variables
env:
  - OMP_NUM_THREADS=4
# Build steps
script:
  - aclocal
  - automake --add-missing
  - autoconf
  - ./configure
  - make
  - ./par2 -h
  - make check
  - make distcheck
