.\" Manpage for par2
.\" Contact ike.devolder@gmail.com for mistakes.
.TH par2 1 "may 2015" "0.6.14" "Parity archive utils"
.SH NAME
par2 \- PAR 2.0 compatible file verification and repair tool.
.SH SYNOPSIS
.B par2 c|v|r
.RI "[options] <" "par2 file" "> [" "files" "]"
.br

.B par2 c(reate)
.RI "[options] <" "par2 file" "> [" "files" "]"
.br
.B par2 v(erify)
.RI "[options] <" "par2 file" "> [" "files" "]"
.br
.B par2 r(epair)
.RI "[options] <" "par2 file" "> [" "files" "]"
.br

Also:
.br
.B par2create
.RI "[options] <" "par2 file" "> [" "files" "]"
.br
.B par2verify
.RI "[options] <" "par2 file" "> [" "files" "]"
.br
.B par2repair
.RI "[options] <" "par2 file" "> [" "files" "]"
.br
.SH DESCRIPTION
par2cmdline is a program for creating and using PAR2 files to detect damage in data files and repair them if necessary. It can be used with any kind of file.
.SH OPTIONS
.TP
.B \-h
Show this help
.TP
.B \-V
Show version
.TP
.B \-VV
Show version and copyright
.TP
.BI "\-a <" "file" ">"
Set the main par2 archive name; required on create, optional for verify and repair
.TP
.B \-b<n>
Set the Block\(hyCount
.TP
.B \-s<n>
.RB "Set the Block\(hySize (don't use both " "\-b" " and " "\-s" ")"
.TP
.B \-r<n>
Level of redundancy (percentage)
.TP
.B \-r<c><n>
Redundancy target size, <c>=g(iga),m(ega),k(ilo) bytes
.TP
.B \-c<n>
.RB "Recovery block count (don't use both " "\-r" " and " "\-c" ")"
.TP
.B \-f<n>
First Recovery\(hyBlock\(hyNumber
.TP
.B \-u
Uniform recovery file sizes
.TP
.B \-l
.RB "Limit size of recovery files (don't use both " "\-u" " and " "\-l" ")"
.TP
.B \-n<n>
.RB "Number of recovery files (don't use both " "\-n" " and " "\-l" ")"
.TP
.B \-m<n>
Memory (in MB) to use
.TP
.B \-v [\-v]
Be more verbose
.TP
.B \-q [\-q]
.RB "Be more quiet (" "\-qq" " gives silence)"
.TP
.B \-p
Purge backup files and par files on successful recovery or when no recovery is needed
.TP
.B \-R
Recurse into subdirectories (only useful on create)
.TP
.B \-N
data skipping (find badly mispositioned data blocks)
.TP
.B \-S<n>
Skip leaway (distance +/\- from expected block position)
.TP
.B \-B<path>
Set the basepath to use as reference for the datafiles
.TP
.B \-\-
Treat all remaining command line as filenames
.SH AUTHORS
Peter Brian Clements <peterbclements@users.sourceforge.net>
.br
Marcel Partap <mpartap@gmx.net>
.br
Ike Devolder <ike.devolder@gmail.com>
