#!/bin/sh

cd testdir/subdir || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2

banner="Repairing two files in subdirs using PAR 2.0 data"
dashes=`echo "$banner" | sed s/./-/g`

echo $dashes
echo $banner
echo $dashes

rm -f subdir1/test-2.data subdir2/test-7.data
../../par2 r testdata.par2 > ../test7.log || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
cmp -s subdir1/test-2.data ../test-2.data.orig && cmp -s subdir2/test-7.data ../test-7.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2

exit 0;

