#!/bin/sh

execdir="$PWD"

if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
  srcdir="$PWD"
  TESTDATA="$srcdir/tests"
else
  srcdir="$PWD/$srcdir"
  TESTDATA="$srcdir/tests"
fi

TESTROOT=$PWD

testname=$(basename $0)
rm -f "$testname.log"
rm -rf "run$testname"

mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2

banner="par2 with full path and creation and repair in subfolder"
dashes=`echo "$banner" | sed s/./-/g`

echo $dashes
echo $banner
echo $dashes

mkdir subfolder

echo "file contents" > subfolder/some-file
$execdir/par2 create `pwd`/subfolder/some-file || { echo "ERROR: Failed to create parchive"; exit1; } >&2
echo "corrupted contents" > subfolder/some-file
$execdir/par2 repair subfolder/some-file || { echo "ERROR: Failed to repair"; exit 1; } >&2

cd $TESTROOT
rm -rf run$testname

exit 0;

