#!/bin/sh -x

execdir="$PWD"

if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
  srcdir="$PWD"
  TESTDATA="$srcdir/tests"
else
  srcdir="$PWD/$srcdir"
  TESTDATA="$srcdir/tests"
fi

TESTROOT="$PWD"

testname=$(basename $0)
rm -f "$testname.log"
rm -rf "run$testname"

mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2

banner="par2 with full path"
dashes=`echo "$banner" | sed s/./-/g`

echo $dashes
echo $banner
echo $dashes

echo "file contents" > some-file
"$execdir/par2" create "$(pwd)"/some-file || { echo "ERROR: Failed to create parchive"; exit1; } >&2
echo "corrupted contents" > some-file
"$execdir/par2" repair some-file || { echo "ERROR: Failed to repair"; exit 1; } >&2

cd "$TESTROOT"
rm -rf "run$testname"

exit 0;

