#!/bin/sh

cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
tests=$(realpath .)

testname=$(basename $0)
rm -f $testname.log
rm -rf run$testname

mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2

tar -xzf $tests/flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2

banner="create 5% recovery files"
dashes=`echo "$banner" | sed s/./-/g`

echo $dashes
echo $banner
echo $dashes

../../par2 c testdata.par2 *.data > $tests/$testname.log || { echo "ERROR: creating repair files using PAR 2.0 failed" ; exit 1; } >&2

banner="repair files where 1 byte got removed at the beginning of a file"
dashes=`echo "$banner" | sed s/./-/g`

echo $dashes
echo $banner
echo $dashes

mv test-1.data test-1.data-correct
tail -c 177173 test-1.data-correct > test-1.data

../../par2 r testdata.par2 >> $tests/$testname.log || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2

cd ..
rm -rf run$testname

exit 0;

