#!/bin/sh

execdir="$PWD"

# valgrind tests memory usage.
# wine allow for windows testing on linux
if [ -n "${PARVALGRINDOPTS+set}" ]
then
    PARBINARY="valgrind $PARVALGRINDOPTS $execdir/par2"
elif [ "`which wine`" != "" ] && [ -f "$execdir/par2.exe" ]
then
    PARBINARY="wine $execdir/par2.exe"
else
    PARBINARY="$execdir/par2"
fi


if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
  srcdir="$PWD"
  TESTDATA="$srcdir/tests"
else
  srcdir="$PWD/$srcdir"
  TESTDATA="$srcdir/tests"
fi

TESTROOT="$PWD"

testname=$(basename $0)
rm -f "$testname.log"
rm -rf "run$testname"

mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2

banner="Verify -L (follow symlinks) handling"
dashes=`echo "$banner" | sed s/./-/g`

echo $dashes
echo $banner
echo $dashes

# generate test data and links
echo -n '01234567890abcdef' > test_file
ln -s test_file test_link
mkdir test_dir
ln -s $(pwd)/test_file test_dir/test_link
ln -s test_dir dir_link
ln -s NOT_EXISTING dead_link

# without -L, links are not followed for non-primary files
$PARBINARY c -r10 nofollow test_link && { echo "ERROR: followed link without -L" ; exit 1; } >&2

# test creation with symlink following
echo "*** Create with -L ***"
$PARBINARY c -L -r10 follow_links test_link || { echo "ERROR: creating with -L failed" ; exit 1; } >&2

# the linked data verifies and repairs
echo "*** Verify good file link ***"
$PARBINARY v -q follow_links || { echo "ERROR: verifying good link data failed" ; exit 1; } >&2
cp test_file test_file.bak
echo -n "!" >> test_file
echo "*** Verify damaged file link ***"
$PARBINARY v -q follow_links && { echo "ERROR: verifying damaged link data succeeded" ; exit 1; } >&2
echo "*** Repair ***"
$PARBINARY r -q follow_links || { echo "ERROR: repairing linked data failed" ; exit 1; } >&2
diff test_link test_file.bak || { echo "ERROR: comparison after repairing linked data failed" ; exit 1; } >&2

# with -R -L, links to files inside directories are followed
echo "*** Create recursive with -L ***"
$PARBINARY c -R -L -r10 dirrec test_dir || { echo "ERROR: recursive create with -L failed" ; exit 1; } >&2
$PARBINARY v -q dirrec || { echo "ERROR: verifying recursive link data failed" ; exit 1; } >&2

# linked directories are not followed, even with -R -L
$PARBINARY c -R -L -r10 dirlink dir_link && { echo "ERROR: followed linked directory" ; exit 1; } >&2

# dead links fail, even with -L
$PARBINARY c -L -r10 dead dead_link && { echo "ERROR: calculating dead link data succeeded" ; exit 1; } >&2

echo "\nLink tests succeeded!"

cd "$TESTROOT"
rm -rf "run$testname"

exit 0
