#!/bin/sh

cd $(dirname $0)

testname=$(basename $0)
rm -f $testname.log

mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2

faraway='in/a/folder/far/far/away'

mkdir -p "$faraway" || { echo "ERROR: Could not create fancy folder" ; exit 1; } >&2

tar -xf ../flatdata.tar.gz -C "$faraway" || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
tar -xf ../flatdata-par2files.tar.gz -C "$faraway" || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2

banner="par2 can be run from any starting dir"
dashes=`echo "$banner" | sed s/./-/g`

echo $dashes
echo $banner
echo $dashes

../../par2 v "$faraway"/testdata.par2  > ../$testname.log || { echo "ERROR: verify of PAR 2.0 files failed" ; exit 1; } >&2

cd ..
rm -rf run$testname

exit 0;

