#!/bin/sh

cd $(dirname $0)

testname=$(basename $0)
rm -f $testname.log

mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2

tar -xf ../flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
tar -xf ../flatdata-par2files.tar.gz || { echo "ERROR: Could not extract par test files" ; exit 1; } >&2

banner="rename using PAR 2.0 data"
dashes=`echo "$banner" | sed s/./-/g`

echo $dashes
echo $banner
echo $dashes

mv test-5.data rename
../../par2 r testdata.par2 rename > ../$testname.log || { echo "ERROR: Initial PAR 2.0 verification and rename failed" ; exit 1; } >&2
test -e test-5.data ||  { echo "ERROR: rename failed" ; exit 1; } >&2

cd ..
rm -rf run$testname

exit 0;

