#!/bin/sh

execdir="$PWD"

if [ -n "${PARVALGRINDOPTS+set}" ]
then
    PARBINARY="valgrind $PARVALGRINDOPTS $execdir/par2"
elif [ "`which wine`" != "" ] && [ -f "$execdir/par2.exe" ]
then
    PARBINARY="wine $execdir/par2.exe"
else
    PARBINARY="$execdir/par2"
fi

if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
  srcdir="$PWD"
  TESTDATA="$srcdir/tests"
else
  srcdir="$PWD/$srcdir"
  TESTDATA="$srcdir/tests"
fi

TESTROOT="$PWD"

testname=$(basename $0)
rm -f "$testname.log"
rm -rf "run$testname"

mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2

banner="Rejecting oversized PAR2 source block counts"
dashes=`echo "$banner" | sed s/./-/g`

echo $dashes
echo $banner
echo $dashes

tar -xzf "$TESTDATA/block-count-wrap.tar.gz" || { echo "ERROR: Could not extract PAR2 test file" ; exit 1; } >&2

$PARBINARY r -q recovery.par2 >repair.out 2>repair.err
result=$?

if [ $result -eq 0 ]
then
    echo "ERROR: Repair accepted oversized source block counts" >&2
    exit 1
fi

if [ $result -gt 128 ]
then
    echo "ERROR: Repair terminated by signal instead of rejecting malformed PAR2 data" >&2
    exit 1
fi

grep -q "Too many source blocks in recovery set" repair.err || { echo "ERROR: Expected oversized block count rejection" ; exit 1; } >&2

cd "$TESTROOT"
rm -rf "run$testname"

exit 0
