#!/bin/sh

cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
tests=../../$srcdir/tests

testname=$(basename $0)
rm -f $testname.log
rm -rf run$testname

mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2

cp $tests/flatdata.tar.gz ./ || { echo "ERROR: Could not copy data test files" ; exit 1; } >&2

banner="Creating PAR 2.0 recovery data"
dashes=`echo "$banner" | sed s/./-/g`

echo $dashes
echo $banner
echo $dashes

../../par2 c recovery flatdata.tar.gz > $tests/$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2

banner="Verifying using PAR 2.0 data"
dashes=`echo "$banner" | sed s/./-/g`

echo $dashes
echo $banner
echo $dashes

mv flatdata.tar.gz flatdata.tar.gz-orig
dd if=flatdata.tar.gz-orig bs=1983 count=1 of=flatdata.tar.gz
rm -f flatdata.tar.gz-orig

../../par2 r recovery.par2 ./* >> $tests/$testname.log || { echo "ERROR: PAR 2.0 repair failed" ; exit 1; } >&2

cd ..
rm -rf run$testname

exit 0;

