#!/bin/sh

cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
tests=$PWD

testname=$(basename $0)
rm -f $testname.log
rm -rf run$testname

mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2

tar -xzf $tests/flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
tar -xzf $tests/flatdata-par1files.tar.gz || { echo "ERROR: Could not extract par test files" ; exit 1; } >&2

banner="Verifying using PAR 1.0 data"
dashes=`echo "$banner" | sed s/./-/g`

echo $dashes
echo $banner
echo $dashes

../../par2 v testdata.par > $tests/$testname.log || { echo "ERROR: Initial PAR 1.0 verification failed" ; exit 1; } >&2

cd ..
rm -rf run$testname

exit 0;

