name: par2cmdline CI windows

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-check-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v7

    - name: Build
      run: |
        cmake -B build-cmake -A x64
        cmake --build build-cmake --config Release -j

    - name: Run Tests
      run: ctest --test-dir build-cmake -C Release --output-on-failure
