name: par2cmdline CI Linux (TSan)

on:
  workflow_call:

jobs:
  build-check-tsan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Build and test (TSan)
      run: |
        cmake -B build-cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_FLAGS="-g -O1 -fsanitize=thread" \
          -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=thread"
        cmake --build build-cmake
        ctest --test-dir build-cmake --output-on-failure
