name: par2cmdline CI MacOS

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-check-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v7

    - name: Build and test
      run: |
        cmake -B build-cmake -DCMAKE_BUILD_TYPE=Release -DPAR2_KEEP_ASSERTS=ON
        cmake --build build-cmake -j"$(sysctl -n hw.ncpu)"
        ctest --test-dir build-cmake --output-on-failure
