name: par2cmdline CI MinGW

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-check-mingw:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Install MinGW
      run: sudo apt-get update && sudo apt-get install -y mingw-w64

    - name: Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_SYSTEM_NAME=Windows \
          -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
          -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++
        cmake --build build -j"$(nproc)"
